//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL_WCF.SrvEmpleado {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/SrvEmpleado")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Empleado", Namespace="http://schemas.datacontract.org/2004/07/DAL")]
    [System.SerializableAttribute()]
    public partial class Empleado : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CiudadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoPostalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EmpleadoIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExtensionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PuestoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellido {
            get {
                return this.ApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoField, value) != true)) {
                    this.ApellidoField = value;
                    this.RaisePropertyChanged("Apellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ciudad {
            get {
                return this.CiudadField;
            }
            set {
                if ((object.ReferenceEquals(this.CiudadField, value) != true)) {
                    this.CiudadField = value;
                    this.RaisePropertyChanged("Ciudad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoPostal {
            get {
                return this.CodigoPostalField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoPostalField, value) != true)) {
                    this.CodigoPostalField = value;
                    this.RaisePropertyChanged("CodigoPostal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EmpleadoID {
            get {
                return this.EmpleadoIDField;
            }
            set {
                if ((this.EmpleadoIDField.Equals(value) != true)) {
                    this.EmpleadoIDField = value;
                    this.RaisePropertyChanged("EmpleadoID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Extension {
            get {
                return this.ExtensionField;
            }
            set {
                if ((object.ReferenceEquals(this.ExtensionField, value) != true)) {
                    this.ExtensionField = value;
                    this.RaisePropertyChanged("Extension");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pais {
            get {
                return this.PaisField;
            }
            set {
                if ((object.ReferenceEquals(this.PaisField, value) != true)) {
                    this.PaisField = value;
                    this.RaisePropertyChanged("Pais");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Puesto {
            get {
                return this.PuestoField;
            }
            set {
                if ((object.ReferenceEquals(this.PuestoField, value) != true)) {
                    this.PuestoField = value;
                    this.RaisePropertyChanged("Puesto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Region {
            get {
                return this.RegionField;
            }
            set {
                if ((object.ReferenceEquals(this.RegionField, value) != true)) {
                    this.RegionField = value;
                    this.RaisePropertyChanged("Region");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SrvEmpleado.IServicio")]
    public interface IServicio {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/GetData", ReplyAction="http://tempuri.org/IServicio/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/GetData", ReplyAction="http://tempuri.org/IServicio/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IServicio/GetDataUsingDataContractResponse")]
        BLL_WCF.SrvEmpleado.CompositeType GetDataUsingDataContract(BLL_WCF.SrvEmpleado.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IServicio/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<BLL_WCF.SrvEmpleado.CompositeType> GetDataUsingDataContractAsync(BLL_WCF.SrvEmpleado.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ObtenerEmpleadosLista", ReplyAction="http://tempuri.org/IServicio/ObtenerEmpleadosListaResponse")]
        BLL_WCF.SrvEmpleado.Empleado[] ObtenerEmpleadosLista();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ObtenerEmpleadosLista", ReplyAction="http://tempuri.org/IServicio/ObtenerEmpleadosListaResponse")]
        System.Threading.Tasks.Task<BLL_WCF.SrvEmpleado.Empleado[]> ObtenerEmpleadosListaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ActualizarEmpleado", ReplyAction="http://tempuri.org/IServicio/ActualizarEmpleadoResponse")]
        bool ActualizarEmpleado(BLL_WCF.SrvEmpleado.Empleado empleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ActualizarEmpleado", ReplyAction="http://tempuri.org/IServicio/ActualizarEmpleadoResponse")]
        System.Threading.Tasks.Task<bool> ActualizarEmpleadoAsync(BLL_WCF.SrvEmpleado.Empleado empleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ObtenerEmpleadoDetalle", ReplyAction="http://tempuri.org/IServicio/ObtenerEmpleadoDetalleResponse")]
        BLL_WCF.SrvEmpleado.Empleado ObtenerEmpleadoDetalle(int empID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ObtenerEmpleadoDetalle", ReplyAction="http://tempuri.org/IServicio/ObtenerEmpleadoDetalleResponse")]
        System.Threading.Tasks.Task<BLL_WCF.SrvEmpleado.Empleado> ObtenerEmpleadoDetalleAsync(int empID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/BorrarEmpleado", ReplyAction="http://tempuri.org/IServicio/BorrarEmpleadoResponse")]
        bool BorrarEmpleado(int empID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/BorrarEmpleado", ReplyAction="http://tempuri.org/IServicio/BorrarEmpleadoResponse")]
        System.Threading.Tasks.Task<bool> BorrarEmpleadoAsync(int empID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/AgregarEmpleado", ReplyAction="http://tempuri.org/IServicio/AgregarEmpleadoResponse")]
        bool AgregarEmpleado(BLL_WCF.SrvEmpleado.Empleado empleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/AgregarEmpleado", ReplyAction="http://tempuri.org/IServicio/AgregarEmpleadoResponse")]
        System.Threading.Tasks.Task<bool> AgregarEmpleadoAsync(BLL_WCF.SrvEmpleado.Empleado empleado);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioChannel : BLL_WCF.SrvEmpleado.IServicio, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioClient : System.ServiceModel.ClientBase<BLL_WCF.SrvEmpleado.IServicio>, BLL_WCF.SrvEmpleado.IServicio {
        
        public ServicioClient() {
        }
        
        public ServicioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public BLL_WCF.SrvEmpleado.CompositeType GetDataUsingDataContract(BLL_WCF.SrvEmpleado.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<BLL_WCF.SrvEmpleado.CompositeType> GetDataUsingDataContractAsync(BLL_WCF.SrvEmpleado.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public BLL_WCF.SrvEmpleado.Empleado[] ObtenerEmpleadosLista() {
            return base.Channel.ObtenerEmpleadosLista();
        }
        
        public System.Threading.Tasks.Task<BLL_WCF.SrvEmpleado.Empleado[]> ObtenerEmpleadosListaAsync() {
            return base.Channel.ObtenerEmpleadosListaAsync();
        }
        
        public bool ActualizarEmpleado(BLL_WCF.SrvEmpleado.Empleado empleado) {
            return base.Channel.ActualizarEmpleado(empleado);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarEmpleadoAsync(BLL_WCF.SrvEmpleado.Empleado empleado) {
            return base.Channel.ActualizarEmpleadoAsync(empleado);
        }
        
        public BLL_WCF.SrvEmpleado.Empleado ObtenerEmpleadoDetalle(int empID) {
            return base.Channel.ObtenerEmpleadoDetalle(empID);
        }
        
        public System.Threading.Tasks.Task<BLL_WCF.SrvEmpleado.Empleado> ObtenerEmpleadoDetalleAsync(int empID) {
            return base.Channel.ObtenerEmpleadoDetalleAsync(empID);
        }
        
        public bool BorrarEmpleado(int empID) {
            return base.Channel.BorrarEmpleado(empID);
        }
        
        public System.Threading.Tasks.Task<bool> BorrarEmpleadoAsync(int empID) {
            return base.Channel.BorrarEmpleadoAsync(empID);
        }
        
        public bool AgregarEmpleado(BLL_WCF.SrvEmpleado.Empleado empleado) {
            return base.Channel.AgregarEmpleado(empleado);
        }
        
        public System.Threading.Tasks.Task<bool> AgregarEmpleadoAsync(BLL_WCF.SrvEmpleado.Empleado empleado) {
            return base.Channel.AgregarEmpleadoAsync(empleado);
        }
    }
}
